#!/bin/bash -e

bindir=$(realpath "$(dirname "$0")")
libdir=$(realpath "$bindir/../../lib")

. "$bindir"/functions

USAGE="Usage: $0"

while getopts hb:-: arg; do
    case $arg in
        h) warn "$USAGE"; exit 0 ;;
        #b) ARG_B="$OPTARG" ;;
        -) LONG_OPTARG="${OPTARG#*=}"
            case $OPTARG in
                help)  warn "$USAGE"; exit 0 ;;
                #letter-b=?*)    ARG_B="$LONG_OPTARG" ;;
                #letter-b*)        error "Option '--$OPTARG' requires an argument" ;;
                #letter-a* | letter-c* ) error "Option '--$OPTARG' doesn't allow an argument" ;;
                '')    break ;; # "--" terminates argument processing
                *)     error "Illegal option --$OPTARG" ;;
                esac
        ;;
    esac
done
shift $((OPTIND-1))

GCC="gcc -fPIC -std=c99"

chd "$bindir"
# --- -d to also make header.
cmd bison --report=state -d rh-parse.y
cmd $GCC -c rh-parse.tab.c

chd "$libdir"
chd fish-lib-util
cmd make

chd "$bindir"

cmd $GCC rh-parse.c \
    rh-parse.tab.o \
    "$libdir"/fish-lib-util/fish-util/fish-util.o \
    -lm \
    -o main_test
